name: Testes Robot Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Instalar Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: Instalar ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Iniciar servidor HTTP
      run: |
        nohup python3 -m http.server 8000 &

    - name: Executar testes Robot Framework
      run: |
        robot tests/teste_login.robot

    - name: Armazenar relatórios
      uses: actions/upload-artifact@v4
      with:
        name: relatorios-robot
        path: |
          log.html
          report.html
          output.xml
