name: Testes Robot Framework

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python e dependências
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências com pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Baixar WebDriver (ChromeDriver)
        run: |
          sudo apt install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Rodar servidor HTTP
        run: |
          nohup python3 -m http.server 8000 &

      - name: Executar testes Robot Framework
        run: |
          robot tests/teste_login.robot

      - name: Armazenar relatórios
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-robot
          path: |
            tests/log.html
            tests/report.html
            tests/output.xml
      - name: Exibir mensagem de sucesso
        if: success()
        run: echo "✅ Todos os testes passaram com sucesso!"

      - name: Exibir mensagem de falha
        if: failure()
        run: echo "❌ Um ou mais testes falharam. Verifique os relatórios em log.html ou report.html"
